# Generated by Django 6.0.6 on 2026-06-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_unitario',
            new_name='precio_base',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='tipo_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('metro', 'Metro')], default='unidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='nota',
            field=models.TextField(blank=True, default='Se solicita el 50% de adelanto y el 50% al terminar la instalación.', null=True),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
