# Generated by Django 6.0.6 on 2026-06-27 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_precio_unitario_producto_precio_base_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnidadMedida',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
    ]
