# Generated by Django 6.0.6 on 2026-06-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_delete_unidadmedida_remove_cliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
