# Generated by Django 6.0.6 on 2026-06-27 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_cotizacion_numero_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='concepto',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.producto'),
        ),
    ]
